version: '{branch}-{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_branch_with_pr: true
image: Visual Studio 2017
install:
- ps: >-
    If (Test-Path Env:APPVEYOR_REPO_TAG_NAME) {
        ./gradlew clean -PjenkinsBuild -PreleaseType=OFFICIAL --continue --no-daemon
    } Else {
        ./gradlew clean -PjenkinsBuild --continue --no-daemon
    }

cache: C:\Users\appveyor\.gradle
build_script:
- ps: >-
    If (Test-Path Env:APPVEYOR_REPO_TAG_NAME) {
        ./gradlew build -PjenkinsBuild -PreleaseType=OFFICIAL --continue --no-daemon
    } Else {
        ./gradlew build -PjenkinsBuild --continue --no-daemon
    }

test: off
artifacts:
- path: '**/libs/*'
  name: Jars
deploy:
- provider: GitHub
  auth_token:
    secure: jecQI2sLa3l2Ubgls0IS5xeqCezIqisLyC4y8VSm7JZzXM7r+wWc7Fs7aoCQJ51G
  artifact: /.*\.*/
  on:
    appveyor_repo_tag: true

environment:
  publish_key:
    secure: UGuUcPX9W6daDySgBpeip3sK9BgS2CFBd8UEaon92DmAMsQf5QaYv+B6Ctn0JxlQ
  publish_secret:
    secure: Xncoe1fJg66+9tkZa367O1yKhO/3POjad0mY3oXrDzvMzYKPSgt8KVBnQ7wOB198
deploy_script:
- cmd: >-

    if %APPVEYOR_REPO_TAG% equ true if %APPVEYOR_REPO_BRANCH% equ master gradlew.bat publishPlugin -PjenkinsBuild -PreleaseType=OFFICIAL -Pgradle.publish.key=%publish_key% -Pgradle.publish.secret=%publish_secret% --no-daemon
